name: Detectar Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: PR
        if: github.event_name == 'pull_request'
        run: echo "hello pull request"
