name: Minify JavaScript

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  minify_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install minify
        run: npm install minify -g

      - name: Minify JavaScript
        run: minify main.js > main.min.js

      - name: Commit minified file
        uses: stefanzweife/git-auto-commit-action@v5
